-- MySQL Script generated by MySQL Workbench
-- qua 31 ago 2016 20:53:14 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipos_ativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_ativos` (
  `idtipos_ativos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  PRIMARY KEY (`idtipos_ativos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`privilegios` (
  `idprivilegios` INT NOT NULL AUTO_INCREMENT,
  `privilegio` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idprivilegios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  `senha` VARCHAR(45) NULL,
  `privilegio` INT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_privilegios_idx` (`privilegio` ASC),
  CONSTRAINT `fk_user_privilegios`
    FOREIGN KEY (`privilegio`)
    REFERENCES `mydb`.`privilegios` (`idprivilegios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ativos` (
  `idativos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  `tipo` INT NULL,
  `local` VARCHAR(45) NULL,
  `posicao` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`idativos`),
  INDEX `fk_ativos_tipo_idx` (`tipo` ASC),
  CONSTRAINT `fk_ativos_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`tipos_ativos` (`idtipos_ativos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
